name = "BaseTrainingPlan"
uuid = "040d1834-f38b-4f45-a436-19b9da0e3da9"
authors = ["Jonathan Miller jonathan.miller@fieldofnodes.com"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
